/** Common SOC Prime / Uncoder target platforms (value = API `siem_type`, label = display name). */
export const SIEM_FORMATS: { value: string; label: string }[] = [
  { value: 'splunk', label: 'Splunk Query' },
  { value: 'ala', label: 'Microsoft Sentinel Query' },
  { value: 'ala-rule', label: 'Microsoft Sentinel Rule' },
  { value: 'mdatp', label: 'Microsoft Defender for Endpoint' },
  { value: 'qradar', label: 'IBM QRadar Query' },
  { value: 'elasticsearch', label: 'Elasticsearch Query (Lucene)' },
  { value: 'es-eql', label: 'Elasticsearch Query (EQL)' },
  { value: 'humio', label: 'CrowdStrike NG SIEM / LogScale' },
  { value: 'crowdstrike', label: 'CrowdStrike Endpoint Security' },
  { value: 'chronicle-query', label: 'Google SecOps Query' },
  { value: 'chronicle', label: 'Google SecOps Rule (YARA-L)' },
  { value: 'sumologic', label: 'Sumo Logic Query' },
  { value: 'securonix', label: 'Securonix Query' },
  { value: 's1-events', label: 'SentinelOne Events Query' },
  { value: 'carbonblack', label: 'VMware Carbon Black Cloud' },
  { value: 'carbonblack-edr', label: 'VMware Carbon Black EDR' },
  { value: 'fireeye-helix', label: 'FireEye Helix Query' },
  { value: 'rsa_netwitness', label: 'RSA NetWitness Query' },
  { value: 'graylog', label: 'Graylog Query' },
  { value: 'logpoint', label: 'LogPoint Query' },
  { value: 'arcsight-keyword', label: 'ArcSight Query' },
  { value: 'qualys', label: 'Qualys IOC Query' },
  { value: 'cortex-xql-query', label: 'Palo Alto Cortex XSIAM' },
  { value: 'snowflake', label: 'Snowflake Query' },
];
